project:
  type: website

website:
  title: "simple_quarto_website"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.ipynb

format:
  html:
    theme: cosmos
    toc: true



